[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake==3.25.0",
    "nanobind==1.4.0",
    "ninja",
    "numpy",
    "packaging",
    "PyYAML",
]
build-backend = "setuptools.build_meta"
