site_name: IREE
site_url: https://openxla.github.io/iree/
repo_url: https://github.com/openxla/iree
repo_name: openxla/iree

theme:
  name: material
  logo: assets/images/openxla-logo-lockup-white.svg
  logo_alt: IREE
  icon:
    repo: fontawesome/brands/github
  font:
    text: Noto
    code: Noto Sans Mono
  favicon: assets/images/favicon.png

  # Note: this includes symlinks to forked files in third_party/mkdocs-material/
  custom_dir: overrides

  features:
    - content.code.annotate # Allow inline annotations
    - content.code.copy     # Enable copy button
    - content.tabs.link     # Link content tabs across site (e.g. Windows/Linux)

    - navigation.instant  # Ajax-style dynamic loading (faster)
    - navigation.tracking # Update URL in address bar with the active anchor
    - navigation.sections # Group sections without collapsible buttons
    - navigation.tabs     # Show primary sections in tabs below the header
    - navigation.top      # "Back to top" button
    - navigation.indexes  # Section names can link to index.md pages

    # Disabled options (consider enabling as the site changes)
    # - navigation.expand      # When 'sections' is disabled, start expanded
    # - navigation.tabs.sticky # Keep tabs visible at the top when scrolled

    - toc.follow # Scroll the TOC panel to follow the reader

  palette:
    # Light mode (scheme overrides in openxla.css)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode (scheme overrides in openxla.css)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  # TODO(scotttodd): https://openxla.github.io/community (when hosted)
  community_homepage: https://github.com/openxla/community
  community_site_name: OpenXLA

  # TODO(scotttodd): join mkdocs-material insiders and remove notice?
  #   (we *can* remove the notice without joining)
  # generator: false

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/openxla/iree
      name: IREE on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/26P4xW4
      name: IREE Discord Server
    - icon: fontawesome/solid/users
      link: https://groups.google.com/forum/#!forum/iree-discuss
      name: IREE Discuss Google Group

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/openxla.css

copyright: Copyright &copy; 2023 The IREE Authors

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:  # Table of Contents
      permalink: 'link'  # Use Material font's "link" icon; see openxla.css

# Navigation with explicit ordering and nesting.
# https://www.mkdocs.org/user-guide/configuration/#nav
# Note: may include external links and titles are optional for internal links
nav:
  - Home: "index.md"
  - "Building from source":
      - "building-from-source/index.md"
      - "building-from-source/getting-started.md"
      - "building-from-source/android.md"
      - "building-from-source/ios.md"
      - "building-from-source/riscv.md"
  - "Guides":
      - "guides/index.md"
      - "ML frameworks":
          - "guides/ml-frameworks/index.md"
          - TensorFlow: "guides/ml-frameworks/tensorflow.md"
          - TensorFlow Lite: "guides/ml-frameworks/tflite.md"
          - JAX: "guides/ml-frameworks/jax.md"
          - PyTorch: "guides/ml-frameworks/pytorch.md"
      - "Deployment configurations":
          - "guides/deployment-configurations/index.md"
          - CPU: "guides/deployment-configurations/cpu.md"
          - CPU - Bare-Metal: "guides/deployment-configurations/bare-metal.md"
          - GPU - Vulkan: "guides/deployment-configurations/gpu-vulkan.md"
          - GPU - CUDA/ROCm: "guides/deployment-configurations/gpu-cuda-rocm.md"
  - "Reference":
      - "reference/index.md"
      - "API bindings":
          - "reference/bindings/index.md"
          - Runtime C API: "reference/bindings/c-api.md"
          - Python: "reference/bindings/python.md"
          - TensorFlow Lite: "reference/bindings/tensorflow-lite.md"
      - "Other topics":
          - Glossary: "reference/glossary.md"
          - Optimization options: "reference/optimization-options.md"
          - Extensions: "reference/extensions.md"
  - "Community":
      - "community/index.md"
      - "Blog":
          - "community/blog/index.md"
          - CUDA backend: "community/blog/2021-10-15-cuda-backend.md"
          - Work in progress on Matrix Multiplication on CPU: "community/blog/2021-10-13-mmt4d.md"
          - TFLite Support via TOSA: "community/blog/2021-07-19-tflite-tosa.md"

plugins:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
  - search

  # https://github.com/mkdocs/mkdocs-redirects
  - redirects:
      redirect_maps:  # old -> new
        "extensions/index.md": "reference/extensions.md"

        # "getting-started/" moved under "guides/ml-frameworks/"
        "getting-started/index.md": "guides/ml-frameworks/index.md"
        "getting-started/tensorflow.md": "guides/ml-frameworks/tensorflow.md"
        "getting-started/tflite.md": "guides/ml-frameworks/tflite.md"
        "getting-started/jax.md": "guides/ml-frameworks/jax.md"
        "getting-started/pytorch.md": "guides/ml-frameworks/pytorch.md"

        # "deployment-configurations/" moved under "guides/"
        "deployment-configurations/index.md": "guides/deployment-configurations/index.md"
        "deployment-configurations/cpu.md": "guides/deployment-configurations/cpu.md"
        "deployment-configurations/bare-metal.md": "guides/deployment-configurations/bare-metal.md"
        "deployment-configurations/gpu-vulkan.md": "guides/deployment-configurations/gpu-vulkan.md"
        "deployment-configurations/gpu-cuda-rocm.md": "guides/deployment-configurations/gpu-cuda-rocm.md"

        # "bindings/" moved under "reference/"
        "bindings/index.md": "reference/bindings/index.md"
        "bindings/c-api.md": "reference/bindings/c-api.md"
        "bindings/python.md": "reference/bindings/python.md"
        "bindings/tensorflow-lite.md": "reference/bindings/tensorflow-lite.md"

        # "blog/" moved under "community/"
        "blog/index.md": "community/blog/index.md"
        "blog/2021-07-19-tflite-tosa.md": "community/blog/2021-07-19-tflite-tosa.md"
        "blog/2021-10-13-mmt4d.md": "community/blog/2021-10-13-mmt4d.md"
        "blog/2021-10-15-cuda-backend.md": "community/blog/2021-10-15-cuda-backend.md"
