# This has a silly name to make it sort after the other issue templates
name: 📄 Blank Issue
description: If you know what you're doing (especially collaborators)
body:
  - type: markdown
    attributes:
      value: |
        Please remember to add appropriate labels, assignees, projects, etc.
  - type: textarea
    id: body
    attributes:
      label: "Issue body"
