[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "iree"
authors = [
  {name = "IREE Authors"},
]
description = "IREE compiler and runtime meta package"
readme = "README.md"
license = {text = "Apache-2.0"}
classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
requires-python = ">= 3.9"
# Version is set via the `setup.py` and requirements are set via files below.
dynamic = ["version", "dependencies"]

[project.urls]
Homepage = "https://iree.dev"
Repository = "https://github.com/iree-org"

[tool.setuptools]
packages = []

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
