# Copyright 2024 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI - Linux x64 clang debug

on:
  pull_request:
    paths:
      - ".github/workflows/ci_linux_x64_clang_debug.yml"
  schedule:
    # Weekday mornings at 09:15 UTC = 01:15 PST (UTC - 8).
    - cron: "15 9 * * 1-5"
  workflow_dispatch:

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  # This may run out of memory / disk space on standard GitHub-hosted runners,
  # so run on self-hosted CPU build runners instead.
  linux_x64_clang_debug:
    needs: setup
    runs-on: azure-linux-scale
    container: ghcr.io/iree-org/cpubuilder_ubuntu_jammy@sha256:78a558b999b230f7e1da376639e14b44f095f30f1777d6a272ba48c0bbdd4ccb
    defaults:
      run:
        shell: bash
    env:
      BUILD_DIR: build-debug
      SCCACHE_AZURE_CONNECTION_STRING: "${{ secrets.AZURE_CCACHE_CONNECTION_STRING }}"
      SCCACHE_AZURE_BLOB_CONTAINER: ccache-container
      SCCACHE_CACHE_ZSTD_LEVEL: 10
      SCCACHE_AZURE_KEY_PREFIX: "ci_linux_x64_clang_debug"
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
      - name: Install Python requirements
        run: python3 -m pip install -r ./runtime/bindings/python/iree/runtime/build_requirements.txt
      - name: CMake - configure
        run: |
          source ./build_tools/cmake/setup_sccache.sh
          cmake \
            -G Ninja \
            -B ${BUILD_DIR} \
            -DPython3_EXECUTABLE="$(which python3)" \
            -DCMAKE_BUILD_TYPE=Debug \
            -DIREE_BUILD_PYTHON_BINDINGS=ON \
            -DIREE_ENABLE_LLD=ON \
            -DIREE_ENABLE_ASSERTIONS=ON
      - name: CMake - build
        run: |
          cmake --build ${BUILD_DIR} -- -k 0
          sccache --show-stats
      # We could build `iree-test-deps` or run some unit tests here, but the
      # main thing we want coverage for is the build itself and those steps
      # would add 10+ minutes to the job.
