# Copyright 2024 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI - Linux x64 clang

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  linux_x64_clang:
    needs: setup
    if: contains(fromJson(needs.setup.outputs.enabled-jobs), 'linux_x64_clang')
    runs-on: azure-linux
    container: ghcr.io/iree-org/cpubuilder_ubuntu_jammy_x86_64@sha256:ba10d33ef502d8b33aaa43800e640a6866983ef353b73fda2ed6595c4275e066
    defaults:
      run:
        shell: bash
    env:
      BUILD_DIR: build
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@v4.1.7
        with:
          submodules: true
      - name: Install Python requirements
        run: python3 -m pip install -r ./runtime/bindings/python/iree/runtime/build_requirements.txt
      # TODO(#18238): add local or remote ccache
      - name: CMake - configure
        run: |
          cmake \
            -G Ninja \
            -B ${BUILD_DIR} \
            -DPython3_EXECUTABLE="$(which python3)" \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DIREE_BUILD_PYTHON_BINDINGS=ON \
            -DIREE_ENABLE_LLD=ON \
            -DIREE_ENABLE_ASSERTIONS=ON \
            -DIREE_BUILD_DOCS=ON \
            -DIREE_TARGET_BACKEND_WEBGPU_SPIRV=ON
      - name: CMake - build
        run: |
          cmake --build ${BUILD_DIR} -- -k 0
          cmake --build ${BUILD_DIR} --target install -- -k 0
          cmake --build ${BUILD_DIR} --target iree-test-deps -- -k 0
      - name: Run CTest
        run: ./build_tools/cmake/ctest_all.sh "${BUILD_DIR}"
      - name: Test iree-dialects
        run: ./build_tools/cmake/test_iree_dialects.sh "${BUILD_DIR}"
