# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# This part of the CI handles testing native CI artifacts, allowing reuse of
# the build workflow across configurations. This workflow is triggered by the
# orchiestrating workflow in ci.yml.
name: Test Native CI Artifacts

on:
  workflow_call:
    inputs:
      build-dir:
        description: "Directory name with build artifacts"
        required: true
        type: string
      build-dir-archive:
        description: "Archive name containing build artifacts"
        required: true
        type: string
      gcs-artifact:
        description: "GCS link for the build artifact archive"
        required: true
        type: string

jobs:
  build_all:
    runs-on:
      # Hacks, and order matters. See the comment at the top of ci.yml.
      - self-hosted
      - runner-group=${{ github.event_name == 'pull_request' && 'presubmit' || 'postsubmit' }}
      - cpu
      - os-family=Linux
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2
        with:
          submodules: true
      - name: "Downloading build dir archive"
        run: gcloud alpha storage cp "${{ inputs.gcs-artifact }}" "${{ inputs.build-dir-archive }}"
      - name: "Extracting archive"
        run: tar -xf "${{ inputs.build-dir-archive }}"
      - name: "Testing all"
        run: |
          ./build_tools/github_actions/docker_run.sh \
            --env IREE_CUDA_DISABLE=1 \
            gcr.io/iree-oss/swiftshader@sha256:542de3bac7f6173add3651f75c4c681f4a8e2d23815332dd82afe85c7d598445 \
            ./build_tools/cmake/ctest_all.sh \
            "${{ inputs.build-dir }}"
