# Copyright 2024 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: PkgCI Test AMD MI250
on:
  workflow_call:
    inputs:
      artifact_run_id:
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      artifact_run_id:
        type: string
        default: ""

jobs:
  test:
    runs-on: nodai-amdgpu-mi250-x86-64
    env:
      PACKAGE_DOWNLOAD_DIR: ${{ github.workspace }}/.packages
      BUILD_DIR: build-tests
      VENV_DIR: ${{ github.workspace }}/.venv
      IREE_CPU_DISABLE: 1
      IREE_VULKAN_DISABLE: 1
      IREE_CUDA_DISABLE: 1
      IREE_HIP_DISABLE: 0
      IREE_HIP_TEST_TARGET_CHIP: "gfx90a"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.7
        with:
          submodules: false
      - name: Check out runtime submodules
        run: ./build_tools/scripts/git/update_runtime_submodules.sh
      - uses: actions/setup-python@v5.1.0
        with:
          # Must match the subset of versions built in pkgci_build_packages.
          python-version: "3.11"
      - uses: actions/download-artifact@v4.1.7
        with:
          name: linux_x86_64_release_packages
          path: ${{ env.PACKAGE_DOWNLOAD_DIR }}
      - name: Setup base venv
        run: |
          ./build_tools/pkgci/setup_venv.py ${VENV_DIR} \
            --artifact-path=${PACKAGE_DOWNLOAD_DIR} \
            --fetch-gh-workflow=${{ inputs.artifact_run_id }}
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake clang ninja-build libstdc++-12-dev
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Build in-tree tests
        run: ./build_tools/pkgci/build_tests_using_package.sh ${VENV_DIR}/bin
      - name: Run in-tree GPU tests
        env:
          CTEST_PARALLEL_LEVEL: 2
          IREE_CTEST_LABEL_REGEX: ^requires-gpu|^driver=hip$
          IREE_AMD_RDNA3_TESTS_DISABLE: 1
          IREE_NVIDIA_GPU_TESTS_DISABLE: 0
          IREE_NVIDIA_SM80_TESTS_DISABLE: 1
          IREE_MULTI_DEVICE_TESTS_DISABLE: 0
        run: ./build_tools/cmake/ctest_all.sh ${BUILD_DIR}

      - name: Checkout test suites repository
        uses: actions/checkout@v4.1.7
        with:
          repository: ScottTodd/iree-test-suites
          ref: dc027ded6175dbd753ac08d6d76ba7be36494730
          path: iree-test-suites
      - name: Configure out-of-tree test suite CMake project
        run: |
          source ${VENV_DIR}/bin/activate
          cmake -G Ninja -S iree-test-suites/matmul -B build/ \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DIREE_USE_LOCAL_REPO=ON \
            -DIREE_LOCAL_REPO_PATH=${GITHUB_WORKSPACE} \
            -DIREE_HOST_BIN_DIR=${VENV_DIR}/bin \
            -DIREE_HAL_DRIVER_LOCAL_SYNC=OFF \
            -DIREE_HAL_DRIVER_LOCAL_TASK=OFF \
            -DIREE_HAL_DRIVER_HIP=ON \
            -DIREE_HAL_DRIVER_VULKAN=OFF \
            -DIREE_HAL_DRIVER_METAL=OFF \
            -DIREE_HAL_DRIVER_CUDA=OFF \
            -DIREE_HIP_TEST_TARGET_CHIP=gfx90a
      - name: Build out-of-tree test suite CMake project
        run: cmake --build build/ --target iree-test-suites-matmul-deps
      - name: CTest out-of-tree test suite CMake project
        run: |
          ctest \
            --test-dir build/ -R iree-test-suites \
            --timeout 900 \
            --output-on-failure \
            --no-tests=error \
            --label-regex "^requires-gpu|^driver=hip$" \
            --label-exclude "(^nodocker$|^driver=vulkan$|^driver=metal$|^driver=cuda$|^vulkan_uses_vk_khr_shader_float16_int8$|^requires-gpu-sm80$|^requires-gpu-rdna3$)"
