# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Postsubmit

on: [pull_request]
  # push:
  #   branches:
  #     - main
  # workflow_dispatch:
  # pull_request:  # TODO: DO NOT SUBMIT. remove this

jobs:
  build_runtime:
    uses: ./.github/workflows/build_runtime_cmake.yml
    with:
      build-dir: build-runtime

  test_runtime:
    needs: build_runtime
    uses: ./.github/workflows/test_runtime_cmake.yml
    with:
      build-dir: build-runtime
