# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Post benchmark comment

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit).
  group: ${{ github.event.workflow_run.pull_requests[0].number || github.sha }}-post-benchmark-comment
  cancel-in-progress: true

env:
  PR_CI_STAGE: ${{ github.event.workflow_run.event == 'pull_request' && 'presubmit' || 'postsubmit' }}
  PR_CI_RUN_ID: ${{ github.event.workflow_run.id }}
  PR_CI_RUN_ATTEMPT: ${{ github.event.workflow_run.run_attempt }}

jobs:
  setup:
    if: env.PR_CI_STAGE == 'presubmit'
    runs-on: ubuntu-20.04
    outputs:
      should-run: ${{ steps.configure.outputs.should-run }}
      runner-env: ${{ steps.configure.outputs.runner-env }}
      runner-group: ${{ steps.configure.outputs.runner-group }}
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
        with:
          # We need the parent commit to do a diff
          fetch-depth: 2
      - name: "Configuring CI options"
        id: configure
        run: |
          # Just informative logging. There should only be two commits in the
          # history here, but limiting the depth helps when copying from a local
          # repo instead of using checkout, e.g. with
          # https://github.com/nektos/act where there will be more.
          git log --oneline --graph --max-count=3
          ./build_tools/github_actions/configure_ci.py

  check_benchmark_job:
    needs: setup
    if: needs.setup.outputs.should-run == 'true'
    runs-on: ubuntu-20.04
    outputs:
      job-conclusion: ${{ steps.check.outputs.job-conclusion }}
    steps:
      - name: "Checking benchmark processing job"
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BENCHMARK_PROCESS_JOB: process_benchmark_results
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            --jq ".jobs | map(select(.name==\"${BENCHMARK_PROCESS_JOB}\"))[0] | .conclusion" \
            "/repos/${GITHUB_REPOSITORY}/actions/runs/${PR_CI_RUN_ID}/attempts/${PR_CI_RUN_ATTEMPT}/jobs" \
            > conclusion
          echo "job-conclusion=$(cat conclusion)" >> "${GITHUB_OUTPUT}"

  post_benchmark_comment:
    needs: [setup, check_benchmark_job]
    # TODO(#11076): Temporarily disabled until we migrate the database.
    if: true &&
      needs.setup.outputs.should-run == 'true' &&
      needs.check_benchmark_job.outputs.job-conclusion == 'success'
    runs-on:
      - self-hosted  # must come first
      - runner-group=${{ needs.setup.outputs.runner-group }}
      - environment=${{ needs.setup.outputs.runner-env }}
      - cpu
      - os-family=Linux
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2
      - name: "Downloading artifacts"
        id: download
        env:
          PR_CI_GCS_DIR: gs://iree-github-actions-${{ env.PR_CI_STAGE }}-artifacts/${{ env.PR_CI_RUN_ID }}/${{ env.PR_CI_RUN_ATTEMPT }}
          BENCHMARK_COMMENT_ARTIFACT: benchmark-comment.json
        run: |
          gcloud alpha storage cp \
            "${PR_CI_GCS_DIR}/${BENCHMARK_COMMENT_ARTIFACT}" \
            "${BENCHMARK_COMMENT_ARTIFACT}"
          echo "benchmark-comment-artifact=${BENCHMARK_COMMENT_ARTIFACT}" >> "${GITHUB_OUTPUT}"
      - name: Posting comments
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_ACCESS_TOKEN }}
          GIST_BOT_USER: github-actions-bot
          GIST_BOT_TOKEN: ${{ secrets.GIST_BOT_TOKEN }}
          # Get PR number from the event instead of the untrusted comment
          # artifact, to make sure we won't incorrectly update other PRs.
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
          BENCHMARK_COMMENT_ARTIFACT: ${{ steps.download.outputs.benchmark-comment-artifact }}
        run: |
          ./build_tools/benchmarks/post_benchmark_comment.py \
            --verbose \
            --pr_number "${PR_NUMBER}" \
            "${BENCHMARK_COMMENT_ARTIFACT}"
