# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Presubmit

on:
  workflow_dispatch:
  pull_request:

jobs:
  build_runtime:
    uses: ./.github/workflows/build_runtime_cmake.yml
    with:
      build-dir: build-runtime

  test_runtime:
    needs: build_runtime
    uses: ./.github/workflows/test_runtime_cmake.yml
    with:
      build-dir: build-runtime

  tsan:
    uses: ./.github/workflows/tsan.yml

  summary:
    runs-on: ubuntu-20.04
    needs: [build_runtime, test_runtime, tsan]
    if: always()
    steps:
      - name: Getting combined job status
        run: |
          echo '${{ toJson(needs.*.result) }}' \
            | jq --exit-status 'all(.=="success")' > /dev/null
