name: Process (re)opened issues

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  add-to-project:
    name: Adding issue to the master project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/google/projects/20
          github-token: ${{ secrets.WRITE_ACCESS_TOKEN }}
