# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# Workflow for running `mmperf` (https://github.com/mmperf/mmperf).
# `mmperf` benchmarks matrix-multiply workloads on IREE and other backends such
# as RUY, TVM, Halide, CuBLAS, etc.
#
# The workflow runs benchmarks on CPU and GPU and uploads results to the
# `mmperf-benchmark-artifacts` GC bucket.

name: mmperf

on:
  workflow_dispatch:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-20.04
    env:
      # The commit being checked out is the merge commit for the PR. Its first
      # parent will be the tip of main.
      BASE_REF: HEAD^
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_BODY: ${{ github.event.pull_request.body }}
    outputs:
      should-run: ${{ steps.configure.outputs.should-run }}
      runner-env: ${{ steps.configure.outputs.runner-env }}
      runner-group: ${{ steps.configure.outputs.runner-group }}
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2
        with:
          # We need the parent commit to do a diff
          fetch-depth: 2
      - name: "Configuring CI options"
        id: configure
        run: |
          # Just informative logging. There should only be two commits in the
          # history here, but limiting the depth helps when copying from a local
          # repo instead of using checkout, e.g. with
          # https://github.com/nektos/act where there will be more.
          git log --oneline --graph --max-count=3
          ./build_tools/github_actions/configure_ci.py

  benchmark_cpu:
    needs: setup
    if: needs.setup.outputs.should-run == 'true'
    runs-on:
      - self-hosted  # must come first
      - runner-group=${{ needs.setup.outputs.runner-group }}
      - environment=${{ needs.setup.outputs.runner-env }}
      - cpu
      - os-family=Linux
    env:
      MMPERF_REPO_DIR: "/usr/local/src/mmperf/mmperf"
      MMPERF_BUILD_DIR: "/usr/local/src/mmperf/mmperf-build-cpu"
      MMPERF_RESULTS_DIR: "mmperf-results-cpu"
      GCS_UPLOAD_DIR: "gs://mmperf-benchmark-artifacts/cpu"
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2
        with:
          submodules: true
      - name: "Running mmperf on CPU"
        run: |
          mkdir ${MMPERF_RESULTS_DIR}
          ./build_tools/github_actions/docker_run.sh \
            gcr.io/iree-oss/mmperf@sha256:804448959a4045f390d349cd8913d26556d7b93164aa6e85c2d1b4747a43b9ca \
          ./build_tools/benchmarks/mmperf/run_mmperf.sh "${MMPERF_REPO_DIR}" "${MMPERF_BUILD_DIR}" "${MMPERF_RESULTS_DIR}" "cpu"
      - name: "Uploading artifacts"
        run: |
          pushd ${MMPERF_REPO_DIR}/external/iree
          export IREE_SHA="$(git rev-parse --short=4 HEAD)"
          popd
          export GCS_DIR_NAME="$(date +'%Y-%m-%d').sha_${IREE_SHA}.timestamp_$(date +'%s')"
          gcloud storage cp ${MMPERF_RESULTS_DIR}/latest/**" "${GCS_UPLOAD_DIR}/${GCS_DIR_NAME}/"

  benchmark_cuda:
    needs: setup
    if: needs.setup.outputs.should-run == 'true'
    runs-on:
      - self-hosted  # must come first
      - runner-group=${{ needs.setup.outputs.runner-group }}
      - environment=${{ needs.setup.outputs.runner-env }}
      - gpu
      - os-family=Linux
    env:
      MMPERF_REPO_DIR: "/usr/local/src/mmperf/mmperf"
      MMPERF_BUILD_DIR: "/usr/local/src/mmperf/mmperf-build-cuda"
      MMPERF_RESULTS_DIR: "mmperf-results-cuda"
      GCS_UPLOAD_DIR: "gs://mmperf-benchmark-artifacts/cuda"
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2
        with:
          submodules: true
      - name: "Running mmperf on GPU"
        run: |
          mkdir ${MMPERF_RESULTS_DIR}
          ./build_tools/github_actions/docker_run.sh \
            --gpus all \
            gcr.io/iree-oss/mmperf@sha256:804448959a4045f390d349cd8913d26556d7b93164aa6e85c2d1b4747a43b9ca \
          ./build_tools/benchmarks/mmperf/run_mmperf.sh "${MMPERF_REPO_DIR}" "${MMPERF_BUILD_DIR}" "${MMPERF_RESULTS_DIR}" "cuda"
      - name: "Uploading artifacts"
        run: |
          pushd ${MMPERF_REPO_DIR}/external/iree
          export IREE_SHA="$(git rev-parse --short=4 HEAD)"
          popd
          export GCS_DIR_NAME="$(date +'%Y-%m-%d').sha_${IREE_SHA}.timestamp_$(date +'%s')"
          gcloud alpha storage cp ${MMPERF_RESULTS_DIR}/latest/**" "${GCS_UPLOAD_DIR}/${GCS_DIR_NAME}/"
