# Copyright 2023 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: MI300 Testing
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_mi300_ci:
    name: "test_mi300_ci"
    runs-on: nodai-amdgpu-mi300-x86-64
    env:
      LD_LIBRARY_PATH: /home/esaimana/Python-3.11.9
    steps:
      - name: Checking out IREE repository
        uses: actions/checkout@v4.1.7
        with:
          submodules: false
      - name: Test MI300 machine
        run: |
          sudo export LD_LIBRARY_PATH=/home/esaimana/Python-3.11.9
          sudo echo $USER
          sudo rocm-smi
          sudo rocminfo
          sudo python3 -m venv test_venv
          sudo source test_venv/bin/activate
          sudo pip install --upgrade pip
          sudo pip install iree-compiler
          sudo pip install iree-runtime
          sudo iree-run-module --dump_devices=hip
