# Copyright 2023 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: MI300 Testing
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_mi300_ci:
    name: "test_mi300_ci"
    runs-on: nodai-amdgpu-mi300-x86-64
    env:
      LD_LIBRARY_PATH: /home/esaimana/Python-3.11.9
    steps:
      - name: Checking out IREE repository
        uses: actions/checkout@v4.1.7
        with:
          submodules: false
      - name: Test MI300 machine
        run: |
          sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH echo $USER
          sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH rocm-smi
          sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH rocminfo
          sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH python3 -m venv test_venv
          sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH source test_venv/bin/activate
          sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH pip install --upgrade pip
          sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH pip install iree-compiler
          sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH pip install iree-runtime
          sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH iree-run-module --dump_devices=hip
